求平均值(期望值)

In [1]:
from numpy import array
from numpy import mean
v = array([1,2,3,4,5,6])
print(v)
result = mean(v)
print(result)

[1 2 3 4 5 6]
3.5


行與列的平均值

In [2]:
from numpy import array
from numpy import mean
M = array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(M)
col_mean = mean(M, axis=0)
print("行平均：")
print(col_mean)
row_mean = mean(M, axis=1)
print("列平均：")
print(row_mean)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
行平均：
[1. 2. 3. 4. 5. 6.]
列平均：
[3.5 3.5]


求變異數(方差)

In [5]:
from numpy import array
from numpy import var
v = array([1,2,3,4,5,6])
print(v)
result = var(v, ddof=1)
print("變異數")
print(result)

[1 2 3 4 5 6]
變異數
3.5


計算行標準差與列標準差

In [6]:
from numpy import array
from numpy import std
M = array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(M)
col_mean = std(M, ddof=1, axis=0)
print(col_mean)
row_mean = std(M, ddof=1, axis=1)
print(row_mean)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[0. 0. 0. 0. 0. 0.]
[1.87082869 1.87082869]


求協方差

In [3]:
from numpy import array
from numpy import cov
x = array([1,2,3,4,5,6,7,8,9])
print(x)
y = array([9,8,7,6,5,4,3,2,1])
print(y)
Sigma = cov(x,y)[0,1]
print("兩向量協方差")
print(Sigma)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
兩向量協方差
-7.5


求兩向量相關係數

In [4]:
from numpy import array
from numpy import corrcoef
x = array([1,2,3,4,5,6,7,8,9])
print(x)
y = array([9,8,7,6,5,4,3,2,1])
print(y)
Sigma = corrcoef(x,y)
print(Sigma)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[[ 1. -1.]
 [-1.  1.]]
