# **NDArray** 基本運算及功能簡介

In [ ]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.shape

(2, 3)

In [ ]:
x.dtype

dtype('int32')

In [ ]:
x[1,2]

6

In [ ]:
y = x[:,1]
y

array([2, 5], dtype=int32)

In [ ]:
y[0] = 9
y

array([9, 5], dtype=int32)

In [ ]:
x

array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)

# **# Numpy NDArray 基本運算**

In [ ]:
A = np.array([[3,2],[0,1]])
B = np.array([[3,1],[2,1]])
A+B

array([[6, 3],
       [2, 2]])

In [ ]:
A*B

array([[9, 2],
       [0, 1]])

In [ ]:
A@B

array([[13,  5],
       [ 2,  1]])

In [ ]:
A.dot(B)

array([[13,  5],
       [ 2,  1]])

In [ ]:
A.transpose()

array([[3, 0],
       [2, 1]])

In [ ]:
np.linalg.inv(A)

array([[ 0.33333333, -0.66666667],
       [ 0.        ,  1.        ]])

# **NDarray** **統計功能**

In [ ]:
import numpy as np
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[4.67511302 5.8306368  5.23662839 4.5302857  4.77728861 5.0535762
 5.20500984 4.57895788 5.03124508 5.32208671]


In [ ]:
## Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))

4.530285699255719
5.830636795381895
5.024082821957012
5.042410637801121
0.37984550888881646


In [ ]:
x = np.array([[4, 9, 2, 10],
        [6, 9, 7, 12]])
np.ptp(x, axis=1)

array([8, 6])

In [ ]:
np.ptp(x, axis=0)

array([2, 0, 5, 2])

In [ ]:
np.ptp(x)

10

In [ ]:
a = np.arange(4).reshape((2,2))
np.amin(a)

0

In [ ]:
np.amin(a, axis=0) 

array([0, 1])

In [ ]:
np.amin(a, axis=1) 

array([0, 2])

# **NDArray 維度的運算**

3D Array

In [ ]:
import numpy as np
My3DArray = np.arange(12).reshape(2,2,3)
print (My3DArray)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


3D Array contains 2D info

In [ ]:
import numpy as np
My3DArray1 = np.arange(4).reshape(2,2,1)
print (My3DArray1)

[[[0]
  [1]]

 [[2]
  [3]]]


In [ ]:
My3DArray1 = np.array([[[0],[1]],[[2],[3]]])
print (My3DArray1)

[[[0]
  [1]]

 [[2]
  [3]]]


2D Array

In [ ]:
import numpy as np
My2DArray = np.arange(4).reshape(2,2)
print (My2DArray)

[[0 1]
 [2 3]]


In [ ]:
My2DArray = np.array([[0,1],[2,3]])
print (My2DArray)

[[0 1]
 [2 3]]


Expand Dimension

In [ ]:
y = np.expand_dims(My2DArray, axis=0)
print (y)

[[[0 1]
  [2 3]]]


In [ ]:
y = np.expand_dims(My2DArray, axis=1)
print (y)

[[[0 1]]

 [[2 3]]]


In [ ]:
y = np.expand_dims(My2DArray, axis=2)
print (y)

[[[0]
  [1]]

 [[2]
  [3]]]
