# **NDArray** 基本運算及功能簡介作業解答

In [ ]:
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9]], np.int32)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.shape

(3, 3)

In [ ]:
x.dtype

dtype('int32')

In [ ]:
x[2, 2]

9

In [ ]:
y = x[:,1]
y

array([2, 5, 8], dtype=int32)

In [ ]:
y[0] = 4
y

array([4, 5, 8], dtype=int32)

In [ ]:
x

array([[1, 4, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

# **# Numpy NDArray 基本運算**

In [ ]:
A = np.array([[3,2],[1,0]])
B = np.array([[3,1],[2,4]])
A+B

array([[6, 3],
       [3, 4]])

In [ ]:
A*B

array([[9, 2],
       [2, 0]])

In [ ]:
A@B

array([[13, 11],
       [ 3,  1]])

In [ ]:
A.dot(B)

array([[13, 11],
       [ 3,  1]])

In [ ]:
A.transpose()

array([[3, 1],
       [2, 0]])

In [ ]:
np.linalg.inv(A)

array([[ 0. ,  1. ],
       [ 0.5, -1.5]])

# **NDarray** **統計功能**

In [ ]:
import numpy as np
normal_array = np.random.normal(0, 1, 10)
print(normal_array)

[-0.30829956 -0.43589378 -0.58128601  1.08210309  0.7934439  -0.67655399
  0.5591175   0.87448676 -0.56571132 -0.63229027]


In [ ]:
## Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))

-0.6765539903851607
1.0821030890010424
0.010911631372415765
-0.37209667133824575
0.683896203276413


# **NDArray 維度的運算**

3D Array

In [ ]:
import numpy as np
My3DArray = np.arange(12).reshape(2,3,2)
print (My3DArray)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
