# **NDArray** 基本運算及功能簡介作業
矩陣類別

矩陣形狀

矩陣內容類別

矩陣[x,y]的值

矩陣第x行的值

改變矩陣的值

矩陣加法

矩陣乘法

轉置矩陣

反矩陣

維度變化

In [1]:
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9]], np.int32)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
#矩陣類別
type(x)

numpy.ndarray

In [3]:
#矩陣形狀
x.shape

(3, 3)

In [4]:
#矩陣內容類別
x.dtype

dtype('int32')

In [5]:
#x 矩陣[2,2]的值
x[2,2]

9

In [9]:
#y 矩陣第一行的值
y = x[:,1]
y

array([2, 5, 8])

In [11]:
#y 矩陣第0個值 = 4
y[0] = 4
y

array([4, 5, 8])

# **# Numpy NDArray 基本運算**

In [12]:
A = np.array([[3,2],[1,0]])
B = np.array([[3,1],[2,4]])
#A B 相加
A + B

array([[6, 3],
       [3, 4]])

In [13]:
#A B 元素乘法
A * B

array([[9, 2],
       [2, 0]])

In [17]:
#A B 乘法
np.matmul(A, B)
A @ B

array([[13, 11],
       [ 3,  1]])

In [16]:
#A B 點乘 (elementwise multiplication)
A.dot(B)

array([[13, 11],
       [ 3,  1]])

In [19]:
#A 轉置矩陣
A.T
A.transpose()

array([[3, 1],
       [2, 0]])

In [21]:
#A 反矩陣
np.linalg.inv(A)

array([[ 0. ,  1. ],
       [ 0.5, -1.5]])

# **NDarray** **統計功能**

In [27]:
import numpy as np
normal_array = np.random.normal(0, 1, 10)
print(normal_array)

[-1.94749454 -0.75278723  1.72276396  0.09314433  1.17126966 -0.69803444
 -0.25710759 -1.89412226  0.81818289  0.20786788]


In [28]:
## Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### 中數 Median
print(np.median(normal_array))

### 標準差 Sd
print(np.std(normal_array))

-1.9474945353341804
1.7227639648919666
-0.1536317331260603
-0.08198163020478222
1.1543633944841392


# **NDArray 維度的運算**

3D Array

In [29]:
import numpy as np
# 變成 (2,3,2) 形狀的三維
My3DArray = np.arange(12).reshape(2,3,2)
print (My3DArray)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
