
### 純量，向量，矩陣與張量 之運算 作業

I.基本觀念

1.認識純量(scaler) 將純量60給 x

2.在NumPy中,以陣列(Array)定義向量(Vector) 初始化向量[3, 4, 5]

3.NumPy 印出矩陣x形狀(shape)或大小(size)

4.矩陣(matrix)的定義，運用 brackets 和 commas 分離各列.

5.利用NumPy定義3x3 矩陣 matrix:

6.雖然看不見，但 NumPy 可以很容易定義高維張量(tensor). 以下是如何建立3-D tensor. 4-D, 5-D, 和 6-D tensors 也一樣!

II.NumPy 的 索引 indexing 方式

III.矩陣加法，減法和乘法

IV.轉置矩陣將元素行列位置互換.

V. 產生一個10維的張量

### I. 開始學 NumPy

確認程式庫程式庫版本

In [1]:
import sys
import numpy as np

print ('Python: {}'.format(sys.version))
print ('NumPy: {}'.format(np.__version__))

Python: 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
NumPy: 1.21.5


1.認識純量(scaler)
將純量60給 x

In [2]:
# a scalar
x = 60
x

60

2.在NumPy中,以陣列(Array)定義向量(Vector)
初始化向量[3, 4, 5] 

In [3]:
# a vector [3, 4, 5]
x = np.array((3,4,5))
x

array([3, 4, 5])

3.NumPy 印出矩陣x形狀(shape)或大小(size)

In [4]:
print ('Vector dimensions: {}'.format(x.shape))
print ('Vector size: {}'.format(x.size))

Vector dimensions: (3,)
Vector size: 3


4.矩陣(matrix)的定義，運用  brackets 和 commas 分離各列. 

In [5]:
x = np.array([[7,8,9],[4,5,6],[1,2,3]])
x

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [6]:
print ('Matrix dimensions: {}'.format(x.shape))
print ('Matrix size: {}'.format(x.size))

Matrix dimensions: (3, 3)
Matrix size: 9


5.利用NumPy定義3x3 矩陣 matrix:

In [7]:
x = np.ones((4,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
print ('Matrix dimensions: {}'.format(x.shape))
print ('Matrix size: {}'.format(x.size))

Matrix dimensions: (4, 4)
Matrix size: 16


6.雖然看不見，但 NumPy 可以很容易定義高維張量(tensor). 以下是如何建立3-D tensor. 4-D, 5-D, 和 6-D tensors 也一樣! 

In [9]:
x = np.zeros((3,3,3))
x

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
print('Tensor dimension: {}'.format(x.shape))
print('Tensor size: {}'.format(x.size))

Tensor dimension: (3, 3, 3)
Tensor size: 27


### II. 索引 (Indexing)

1.NumPy 的 索引 indexing 方式

In [14]:
A = np.zeros((5,5), dtype = np.int)
print (A)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


c:\Users\ASUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


In [15]:
# indexing starts at 0
A[0,1] = 2
print (A)

[[0 2 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [16]:
# NumPy用的是列(row) 行(column) 傳統
# 用 : 表示所有列或行
A[:,0] = 3
print (A)

[[3 2 0 0 0]
 [3 0 0 0 0]
 [3 0 0 0 0]
 [3 0 0 0 0]
 [3 0 0 0 0]]


In [18]:
# 高維時增加索引
A = np.ones((5,5,5), dtype = np.int)

# 給第一列設值
A[:,0,0] = 6
print (A)

[[[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


c:\Users\ASUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


### III. 矩陣運算 Matrix Operations

1.矩陣加法，減法和乘法

In [20]:
A = np.matrix([[4,3],[2,1]])
B = np.ones((2,2), dtype = np.int)

c:\Users\ASUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


In [21]:
print (A)

[[4 3]
 [2 1]]


In [22]:
print (B)

[[1 1]
 [1 1]]


In [23]:
# 元素間加法
C = A + B
print (C)

[[5 4]
 [3 2]]


In [24]:
# 元素間減法
C = A - B
print (C)

[[3 2]
 [1 0]]


In [25]:
# 矩陣乘法
C = A @ B
print (C)

[[7 7]
 [3 3]]


### IV. 轉置矩陣 Matrix Transpose

1.轉置矩陣就是將元素行列位置互換.  

In [26]:
A = np.array(range(16))
A = A.reshape(4,4)
print (A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [27]:
# 計算 A 的轉置
B = A.T
print (B)

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [28]:
# 轉置置兩次還原
C = A.T.T
print (C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [29]:
# 轉置可用在任何維度
A = np.array(range(10))
A = A.reshape(2,5)
print (A)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [30]:
# 轉置產生行向量
B = A.T
print (B)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


### V. 高維張量Tensors with Higher Dimensions!

1.產生一個10維的張量

In [31]:
A = np.ones((3,4,3,4,3,2,3,4,3,3))

In [32]:
print (A.shape)
print(len(A.shape))
print (A.size)

(3, 4, 3, 4, 3, 2, 3, 4, 3, 3)
10
93312
