
### 純量，向量，矩陣與張量 

### 1. 開始學 NumPy

確認程式庫程式庫版本

In [1]:
import sys
import numpy as np

print ('Python: {}'.format(sys.version))
print ('NumPy: {}'.format(np.__version__))

Python: 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
NumPy: 1.21.5


認識純量(scaler)

In [2]:
# a scalar
x = 6
x

6

在NumPy中,以陣列(Array)定義向量(Vector) 

In [3]:
# a vector
x = np.array((1,2,3))
x

array([1, 2, 3])

NumPy 矩陣可以定義形狀(shape)或大小(size).

In [4]:
print ('Vector dimensions: {}'.format(x.shape))
print ('Vector size: {}'.format(x.size))

Vector dimensions: (3,)
Vector size: 3


矩陣(matrix)的定義，運用  brackets 和 commas 分離各列. 

In [5]:
x = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
print ('Matrix dimensions: {}'.format(x.shape))
print ('Matrix size: {}'.format(x.size))

Matrix dimensions: (3, 3)
Matrix size: 9


利用NumPy定義3x3 矩陣 matrix:

In [7]:
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
print ('Matrix dimensions: {}'.format(x.shape))
print ('Matrix size: {}'.format(x.size))

Matrix dimensions: (3, 3)
Matrix size: 9


雖然看不見，但 NumPy 可以很容易定義高維張量(tensor). 以下是如何建立3-D tensor. 4-D, 5-D, 和 6-D tensors 也一樣! 

In [9]:
x = np.ones((3,3,3))
x

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [10]:
print ('Tensor dimensions: {}'.format(x.shape))
print ('Tensor size: {}'.format(x.size))

Tensor dimensions: (3, 3, 3)
Tensor size: 27


### 2. 索引 (Indexing)

NumPy 的 索引 indexing 方式

In [11]:
A = np.ones((5,5), dtype = np.int)
print (A)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


c:\Users\ASUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


In [12]:
# indexing starts at 0
A[0,1] = 2
print (A)

[[1 2 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [13]:
# NumPy用的是列(row) 行(column) 傳統
# 用 : 表示所有列或行
A[:,0] = 3
print (A)

[[3 2 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]]


In [14]:
# 高維時增加索引
A = np.ones((5,5,5), dtype = np.int)

# 給第一列設值
A[:,0,0] = 6
print (A)

[[[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


c:\Users\ASUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


### 3. 矩陣運算 Matrix Operations

矩陣加法，減法和乘法

In [15]:
A = np.matrix([[1,2],[3,4]])
B = np.ones((2,2), dtype = np.int)

c:\Users\ASUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


In [16]:
print (A)

[[1 2]
 [3 4]]


In [17]:
print (B)

[[1 1]
 [1 1]]


In [18]:
# 元素間加法
C = A + B
print (C)

[[2 3]
 [4 5]]


In [19]:
# 元素間減法
C = A - B
print (C)

[[0 1]
 [2 3]]


In [20]:
# 矩陣乘法
C = A*B
print (C)

[[3 3]
 [7 7]]


### 4. 轉置矩陣 Matrix Transpose

轉置矩陣就是將元素行列位置互換.  

In [21]:
A = np.array(range(9))
A = A.reshape(3,3)
print (A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [22]:
# calculate tranpose of A
B = A.T
print (B)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [23]:
# taking the tranpose twice will return the original matrix
C = B.T
print (C)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [24]:
# The transpose will work arrays of any dimension
A = np.array(range(10))
A = A.reshape(2,5)
print (A)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [25]:
# create a column vector by taking the transpose
B = A.T
print (B)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


### 5. 高維張量Tensors with Higher Dimensions!

產生一個10維的張量

In [26]:
A = np.ones((3,3,3,3,3,3,3,3,3,3))

In [27]:
print (A.shape)
print(len(A.shape))
print (A.size)

(3, 3, 3, 3, 3, 3, 3, 3, 3, 3)
10
59049
