建立單位矩陣

In [1]:
import numpy as np
x = np.eye(3, 3, dtype = np.int16)
x

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

對稱矩陣與對角矩陣

In [2]:
import numpy as np
np.random.seed(3)
x = np.array([[1, 2, 3],
        [3, 2, 1],
        [2, 1, 2]], dtype = np.int16)
z = np.diag(x)
print ("對角線元素：", z)
y = np.diag(z)
print ("還原為對稱(角)矩陣:\n",y)

對角線元素： [1 2 2]
還原為對稱(角)矩陣:
 [[1 0 0]
 [0 2 0]
 [0 0 2]]


產生與確認正交(Orthogonal)矩陣

In [3]:
from scipy.stats import ortho_group # 需要 scipy 版本至少 0.18
import numpy as np
#產生一3x3正交矩陣
m = ortho_group.rvs(dim=3)
print(m)

[[ 0.97015633 -0.24188991 -0.01691088]
 [ 0.23676398  0.96003285 -0.14926399]
 [ 0.05234046  0.14080551  0.98865276]]


In [4]:
#確認正交姓
np.set_printoptions(suppress=True) #把太小的浮點數印成0
l1 = np.matmul(m, m.T)
print ("matmul(m, m.T)")
print(l1)
print()
print ("matmul(m.T, m)")
l2 = np.matmul(m.T, m)
print(l2)

matmul(m, m.T)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

matmul(m.T, m)
[[ 1. -0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]
