作業1：建立4x4單位矩陣

In [1]:
import numpy as np
x = np.eye(4, 4, dtype = np.int16)
x

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int16)

作業2：找出矩陣找出矩陣對角元素，建立對角矩陣

In [2]:
import numpy as np
np.random.seed(3)
x = np.array([[1, 2, 3, 4],
        [4, 3, 2, 1],
        [4, 3, 2, 1],
        [2, 2, 1, 2]], dtype = np.int16)
z = np.diag(x)
print ("對角線元素：", z)
y = np.diag(z)
print ("還原為對稱(角)矩陣:\n",y)

對角線元素： [1 3 2 2]
還原為對稱(角)矩陣:
 [[1 0 0 0]
 [0 3 0 0]
 [0 0 2 0]
 [0 0 0 2]]


作業3：產生與確認正交(Orthogonal)矩陣

In [12]:
from scipy.stats import ortho_group # 需要 scipy 版本至少 0.18
import numpy as np
#產生一3x3正交矩陣
m = ortho_group.rvs(dim=4, random_state=42)
print(m)

[[ 0.28654116  0.81725347  0.35727908 -0.34977505]
 [-0.07976099  0.0944496   0.61236842  0.78084722]
 [ 0.37363426  0.38245107 -0.66887642  0.51646196]
 [ 0.87859535 -0.4206034   0.22351939 -0.034671  ]]


In [13]:
#確認正交姓
np.set_printoptions(suppress=True) #把太小的浮點數印成0
l1 = np.matmul(m, m.T)
print ("matmul(m, m.T)")
print(l1)
print()
print ("matmul(m.T, m)")
l2 = np.matmul(m.T, m)
print(l2)

matmul(m, m.T)
[[ 1. -0.  0. -0.]
 [-0.  1. -0. -0.]
 [ 0. -0.  1.  0.]
 [-0. -0.  0.  1.]]

matmul(m.T, m)
[[ 1.  0.  0. -0.]
 [ 0.  1. -0. -0.]
 [ 0. -0.  1.  0.]
 [-0. -0.  0.  1.]]
